server:
  host: 0.0.0.0
  port: 2025
  mode: debug
  read_timeout: 10
  write_timeout: 10
  enableGzip: true
  enableAccessLog: true

log:
  logLevel: info
  logFileName: "log/hertz.log"
  logMaxSize: 10
  logMaxAge: 3
  logMaxBackups: 50

mysql:
  user: root
  password: zSpJJ4BhqcucmEF7
  host: 127.0.0.1
  port: 3306
  db_name: test
  charset: utf8mb4
  max_open_conns: 100
  max_idle_conns: 20
  conn_max_lifetime: 30

crawler:
  interval: 30  # 分钟
  targets:
    - https://example.com/data1
    - https://example.com/data2
  
redis:
  addr: 127.0.0.1
  port: 6379
  password:
  db: 0

rabbitmq:
  uri: "amqp://guest:guest@localhost:5672/"
  username: "guest"
  password: "guest"
  exchange: "exchange"
  queue: "queue"
  routing_key: "routing_key"
  consumer_tag: "consumer_tag"
mongodb:
  uri: "mongodb://127.0.0.1:27017"
  db_name: "test"
  collection_name: "test"
  timeout: 10
  max_pool_size: 10
  min_pool_size: 1
  max_idle_time: 10
  max_conn_idle_time: 10
  max_conn_lifetime: 10

websites:
  - name: "website1"
    allowed_domains: ["example1.com", "api.example1.com"]
    accounts:
      - username: user1
        password: pass1
        proxy: http://127.0.0.1:7890
        rate_limit: 2
        authorization:
    interval: 30  # 分钟
    parallelism: 2
    random_delay: 5

  - name: "website2"
    allowed_domains: ["example2.com"]
    accounts:
      - username: "user1"
        password: "pass1"
        proxy: "http://proxy1:port"
        rate_limit: 2s
        authorization:
      - username: "user2"
        password: "pass2"
        proxy: "http://proxy2:port"
        rate_limit: 3s
        authorization:
    interval: 60
    parallelism: 1
    random_delay: 3